def main():
    try:
        var accent = String("é")
        print(accent.count_codepoints(), accent.count_graphemes(), accent[grapheme=0])
        var jamo = String("한")
        print(jamo.count_codepoints(), jamo.count_graphemes(), jamo[grapheme=0])
        var mixed = String("한 x")
        print(mixed.count_graphemes(), mixed[grapheme=0], mixed[grapheme=2])
        var flags = String("\U0001f1fa\U0001f1f8\U0001f1eb\U0001f1f7")
        print(flags.count_graphemes(), flags[grapheme=1])
        var family = String("\U0001f468‍\U0001f469‍\U0001f467")
        print(family.count_graphemes(), family[grapheme=0])
        var thumb = String("\U0001f44d\U0001f3fd")
        print(thumb.count_graphemes(), thumb[grapheme=0])
        var crlf = String("a\r\nb")
        print(crlf.count_graphemes())
        var empty = String("")
        print(empty.count_graphemes())
    except:
        print("unexpected")
    print("done")
